//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.08 at 08:51:34 PM BRST 
//


package br.com.argonavis.filme;

import br.com.argonavis.filme.Filme;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.argonavis.filme package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Filme_QNAME = new QName("http://filme.argonavis.com.br/", "filme");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.argonavis.filme
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filme }
     * 
     */
    public Filme createFilme() {
        return new Filme();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Filme }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://filme.argonavis.com.br/", name = "filme")
    public JAXBElement<Filme> createFilme(Filme value) {
        return new JAXBElement<Filme>(_Filme_QNAME, Filme.class, null, value);
    }

}
